title: Idle Clover
description: My personal documentation for my projects. Not intended for 
theme: just-the-docs

url: https://idleclover.github.io/

callouts:
  issue:
    title: issue
    color: red
  warning:
    title: Warning
    color: yellow
  info:
    title: Info
    color: blue
  success:
    title: Success
    color: green