title: Idle Clover
description: My personal documentation for my projects. Not intended for 
theme: just-the-docs

url: https://idleclover.github.io/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
